name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - jupyterlab=3.6.3
  - tornado=6.1
  - ipywidgets=7.7.2
  - seaborn=0.12.2
  - pandas=1.5.3
  - pip=23.1
  - ydata-profiling=4.1.2
  - pyarrow=11.0.0
  - pip:
      - wandb==0.15.0
