name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - mlflow=2.2.2
  - ipython=8.12.0
  - notebook=6.5.4
  - jupyterlab=3.6.3
  - cookiecutter=2.1.1
  - hydra-core=1.3.2
  - matplotlib=3.5.3
  - pandas=1.5.3
  - git=2.40.1
  - pip=23.1
  - pip:
      - wandb==0.15.0
