name: basic_cleaning
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8.16
  - pandas=1.5.3
  - pip=23.1
  - mlflow=2.2.2
  - scikit-learn=1.2.2
  - matplotlib=3.5.3
  - pillow=9.5.0
  - pip:
      - wandb==0.15.0
